### ISSUE TITLE
ECONNECTREFUSED ERROR

### ISSUE THREAD

**Issue by Zaka-Ullah** [yumauri/gotenberg-js-client#44]
ECCENECT refused error ocurred on 
****const toPDF = pipe(gotenberg('http://localhost:3000/forms/chromium'),convert,html,please)  
toPDF('<html>...</html>').catch(error=>{console.log(error)})****

**Comment by yumauri** [comment]
Hello! Did you actually launch Gotenberg instance on localhost, port 3000?

**Comment by Zaka-Ullah** [comment]
i am running my node Js application on port 3001 and my front end react on
port 3006

**Comment by Zaka-Ullah** [comment]
i have install it on my express server with npm install gotenberg-js-client and import modules according to your latest documentation and error arise of ecconecrefused on port localhost:3000

**Comment by yumauri** [comment]
And also you need to run Gotenberg itself, on localhost, port 3000.
Like this:
```
docker run --rm -p 3000:3000 thecodingmachine/gotenberg:6
```

**Comment by Zaka-Ullah** [comment]
thanks

**Comment by Zaka-Ullah** [comment]
pipe(
  gotenberg(''), // any string here, will be overridden
  convert, // it is save to remove this line, if you want
  office,
  adjust({
    // manually adjust endpoint
    url: 'http://localhost:3500/forms/libreoffice/convert',
  }),
  please
)
What about  now for this url at what endpoint  should we  run our docker on
either on localhost:3000 or localhost:3500

**Comment by yumauri** [comment]
This is up to you and your environment setup.

If you run Gotenberg on port `3000` — use `3000` in connection string.
If you run Gotenberg on other port — use this port in connection string accordingly.
If you run Gotenberg on different machine — use this machine's IP address and port instead of `localhost:××××` (and setup routing).

Note, if you use docker image `thecodingmachine/gotenberg:6` (as I wrote you), you can follow README, this is image with Gotenberg version 6, and library is compatible with it.

If you use docker image `gotenberg/gotenberg:7` (as written in latest [documentation](https://gotenberg.dev)) — only in this case you should use workarounds from [issue #32](https://github.com/yumauri/gotenberg-js-client/issues/32#issuecomment-981140727), for this is Gotenberg version 7.
